### ISSUE TITLE
Multiline matching

### ISSUE THREAD

**Issue by ultraq** [ultraq/thymeleaf-expression-processor#1]
As per https://github.com/ultraq/thymeleaf-layout-dialect/issues/140  Looks like the regex that determines whether an expression is a fragment expression or not doesn't work on multi-line inputs, and so tries to wrap an already proper fragment expression, resulting in further code trying to find templates which include the `~{` part in the name.

**Comment by zhanhb** [comment]
`~/^~{\p{all}+}$/`

**Comment by ultraq** [comment]
That was quick @zhanhb!  I used the `(?s)` flag so that line terminators get matched by the `.`, but I'm curious: what does `\p{all}` do? (I can't seem to find it documented in the java.util.Pattern javadocs)

**Comment by zhanhb** [comment]
I can't find any doc about family pattern \p{all} too. I read the source code of java.util.regexp.Pattern and found that. `(s)` means `dotall` in the pattern. If `dotall` flay is not specified, the dot won't matches line endings.
